---
title: "Miniproyecto-1"
author: "Castro Jimenez"
date: "6/19/2021"
output: html_document
---


```{r cargar datos}
library(tidyverse)
library(readr)
library(skimr)
library(lubridate)
library(gghalves)
Rat_Sightings <- read_csv("Rat_Sightings.csv",na = c("", "NA", "N/A"))


```

```{r manipulacion de datos}
Rat_Sightings<- Rat_Sightings %>% select(-("School or Citywide Complaint":"Ferry Terminal Name") )

rats_clean <- Rat_Sightings %>%
  rename(created_date = `Created Date`,
         location_type = `Location Type`,
         borough = Borough) %>%
  mutate(created_date = mdy_hms(created_date)) %>%
  mutate(sighting_year = year(created_date),
         sighting_month = month(created_date),
         sighting_day = day(created_date),
         sighting_weekday = wday(created_date, label = TRUE, abbr = FALSE)) %>%
  filter(borough != "Unspecified")

rats_clean %>%ggplot(mapping = aes(x=fct_rev(sighting_weekday),fill=borough ))+
  geom_bar()+facet_wrap(vars(borough))+guides(fill=FALSE)+coord_flip()

# Assign a summarized data frame to an object to use it in a plot
rats_by_weekday <- rats_clean %>%
  count(sighting_weekday, sighting_year)

ggplot(data=rats_by_weekday,mapping = aes(x=sighting_weekday,y=n))+
  geom_col()+facet_wrap(vars(sighting_year))+coord_flip()

ggplot(rats_by_weekday, aes(x = fct_rev(sighting_weekday), y = n)) + 
  geom_col() +
  coord_flip() +
  facet_wrap(~ sighting_year,nrow = 2)

# See the count of rat sightings by weekday and borough
rats_clean %>%
  count(sighting_weekday, borough, sighting_year) %>%
  filter(sighting_year>2013,sighting_year<2018) %>% 
  ggplot(mapping = aes(x=sighting_weekday,y=n,fill=borough))+
  geom_col(position = "dodge",width = 0.8)+facet_wrap(vars(sighting_year))+
  scale_fill_brewer(palette = "Set2")+theme_minimal()+coord_flip()

# An alternative to count() is to specify the groups with group_by() and then
# be explicit about how you're summarizing the groups, such as calculating the
# mean, standard deviation, or number of observations (we do that here with
# `n()`).
rats_clean %>%
  group_by(sighting_weekday, borough) %>%mutate(borough=as.factor(borough)) %>% 
  summarize(n = n()) %>% 
  ggplot(mapping = aes(x=sighting_weekday,y=n,fill=borough))+
  geom_col(position = "dodge")+scale_fill_brewer(palette = "Set2")+theme_minimal()+
  xlab(label = NULL)+ylab(label = NULL)

```










